### ISSUE TITLE
cell-swiper灵活性好差

### ISSUE THREAD

**Issue by 1172406997** [tianyong90/we-vue#1]
我希望在开发的时候有更灵活的swiper，但是看你们的官方api以及自己尝试使用但是并不能达到要求，不知道是我的问题还是此组件本身开发就是设置固定的。

**Comment by tianyong90** [comment]
@1172406997 cell-swipe 和 swipe 不是同一个，不确定你指的哪一个组件。如果什么建议可以提出来。

**Comment by 1172406997** [comment]
@tianyong90 嗯，我说的是cell-swipe，我看你们介绍说是参考了mint-ui，但是你们的cell-swipe中内容部分只能写文字内容，个人感觉这样开发十分不方便，嗯，但是依然非常感谢你们开发了这样一个库

**Comment by tianyong90** [comment]
@1172406997 因为到目前为止差不多都是我一个人在写，可能有些方面考虑不周。加上 weui 中 cell-swipe 这个相关的样式是最揎个一版本中才出现的。
在你的应用中，cell-swipe 的按钮中除了文字还会出现什么样的内容呢？

**Comment by 1172406997** [comment]
哇塞，那你很棒棒哟，比如会有list标签，图文混合，在我的项目中目前遇见的是，在cell-wrapper部分需要更高的样式自由度，还有后面button部分，我需要的是icon和字体混合，但是你这版的话因为只能是字体，所以我换回了mint-ui，我在使用mint-ui时同样发现他的cell-wrapper部分有着更高的自由度，但是它的button部分对于宽度的检测始终会在vue中出现问题，我想这些应该对你继续编写这些可能有些许帮助，希望楼主可以更加棒棒哒~~~

**Comment by tianyong90** [comment]
感谢反馈！在随后的版本中会尽量考虑这些场景。如果在使用过程中发现其它问题，欢迎反馈或者 PR。
