### ISSUE TITLE
vue-lazy load error

### ISSUE THREAD

**Issue by jsen-joker** [tianyong90/we-vue#101]
**环境信息:**
 - 设备: [e.g. iPhone6]
 - 浏览器： [e.g. chfome]
 - we-vue 版本： [e.g. v3.0.0]
 - 包管理工具： [npm/yarn]
 - Node.js 版本：

**Bug 描述**  
简要描述 BUG

**重现**  
重现步骤

**预期结果**  
描述预期得到的结果

**截图或代码** 
贴上截图或者相关使用代码，能更清楚的说明问题。

**Comment by tianyong90** [comment]
v3仍在alpha阶段，请别在工作项目中使用。lazyload的问题在开发分支里修复了，尚未发版。

**Comment by tianyong90** [comment]
3.0.0-alpha.7 中已处理
