### ISSUE TITLE
toast message 3.0.0.alpha6

### ISSUE THREAD

**Issue by jsen-joker** [tianyong90/we-vue#102]
toast use a constant value of message
![screen shot 2019-03-01 at 10 40 14](https://user-images.githubusercontent.com/39587248/53612888-3271b700-3c0f-11e9-9f72-0362d314d543.png)

**Comment by tianyong90** [comment]
这个已调整，还没发版。有兴趣的话欢迎一起开发。
v3因为用 TS 重构，然后整体结构上又有不少调整，所以还有些细节要处理。

**Comment by tianyong90** [comment]
3.0.0-alpha.7 中已处理
