### ISSUE TITLE
tab组件使用v-for渲染时，第一次加载不出来内容，需要点击tab切换一次才能显示

### ISSUE THREAD

**Issue by flzyup** [tianyong90/we-vue#105]
**环境信息:**
 - 设备: android, pc
 - OS: android 9, macOS
 - 浏览器： chrome
 - we-vue 版本：2.2.7
 - 包管理工具：yarn
 - Node.js 版本：11.9.0

**Bug 描述**  
在wv-tab上使用v-for条件渲染时，加载页面第一次无法正确展示数据，切换到其他tab再切换回来就有数据了，查询数据请求日志，两种情况下后端返回到数据一致，没有数据丢失问题，应该是tab组件在条件渲染时有问题

**重现**  
重现步骤
使用后端数据接口返回tab数据，并在wv-tab节点上条件渲染

**预期结果**  
希望能正确加载数据

**截图或代码** 
```
<wv-tabs>
      <wv-tab v-bind:key="index" v-for="(tab, index) in worksList" :title="tab.categorie">
        <div style="margin-top: 20px;">
          <ul class="ul2">
            <li class="l1" v-for="(v, index2) in tab.worksList" :key='index2' >
              <div class="grid content-ct">
                <div class="cell">
                  <div class="img-ct">
                    <img :src="v.image" @click="clickViewWorkDetail(v.id)"/>
                    <div class="work-title">&nbsp;&nbsp;{{v.name}}</div>
                  </div>
                  <div class="counts"><span>{{v.voteCount}}票</span><span>{{v.likeCount}}赞</span></div>
                  <div class="vote" @click="fetchVote(v.id,v.voteStatue)">{{voteStatus(v.voteStatue)}}</div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </wv-tab>
    </wv-tabs>
```
![image](https://user-images.githubusercontent.com/158452/54321118-9d1cec80-462a-11e9-9d28-206e5c4bc779.png)
![image](https://user-images.githubusercontent.com/158452/54321123-a6a65480-462a-11e9-8059-1f4897bac736.png)

**Comment by flzyup** [comment]
使用最简单的渲染也是一样的问题
```
<wv-tabs>
      <wv-tab v-bind:key="index" v-for="(tab, index) in worksList" :title="tab.categorie">
        {{tab.categorie}}
      </wv-tab>
    </wv-tabs>
```
worksList为后端数据接口返回的一个array

**Comment by tianyong90** [comment]
@flzyup tabs 需要指定当前激活的 index。这个可以通过 active 属性赋值，或者使用 v-model 来绑定。

**Comment by flzyup** [comment]
我测试下试试 谢谢

**Comment by tianyong90** [comment]
😄

**Comment by flzyup** [comment]
测试过了 不行哦
![image](https://user-images.githubusercontent.com/158452/54437569-ddd24e00-476f-11e9-8a19-89a196a4e2f8.png)
![image](https://user-images.githubusercontent.com/158452/54437582-e2970200-476f-11e9-89d7-9c32a1ef00fc.png)

**Comment by flzyup** [comment]
用:active也是一样

**Comment by tianyong90** [comment]
好的。我检查下。感谢反馈！

**Comment by tianyong90** [comment]
@flzyup  确实是组件初始化逻辑不合理造成的一个 BUG，已经修正并且发布了新版本 2.3.1。请更新下，如果还有其它问题欢迎随时反馈。

**Comment by flzyup** [comment]
@tianyong90 谢谢及时修复！我试试

**Comment by flzyup** [comment]
经测试可以了，另外文档里面并没有写wv-tabs有这个:active属性且是必填的 文档也可以更新下
