### ISSUE TITLE
基础组件Circle，Slots可不可以支持结构？

### ISSUE THREAD

**Issue by anHaoRan** [tianyong90/we-vue#106]
我想要在Circle中使用结构，不知道有什么好的方法吗？
![image](https://user-images.githubusercontent.com/20301207/54891113-3e3b5b00-4ee7-11e9-8caa-b28bb99b2c5e.png)

**Comment by tianyong90** [comment]
抱歉，暂时不行。因为 v2 中这个组件用 svg 实现的，对于中间部分的灵活性考虑不够。v3 有打算重写这一组件，如果有更好的想法或者建议非常欢迎提出。

**Comment by anHaoRan** [comment]
了解
