### ISSUE TITLE
moduleResolution设置为node时，types/lib.d.ts中的@components找不到

### ISSUE THREAD

**Issue by peigong** [tianyong90/we-vue#109]
**环境信息:**
 - 设备: 无
 - OS: linux CentOS
 - 浏览器： 无
 - we-vue 版本：3.0.0-alpha.9
 - 包管理工具： npm、lerna
 - Node.js 版本：v10.15.x

**Bug 描述**  
使用vue-cli v3.x生成的ts工程，编译选项moduleResolution设置为node，`npm run serve`执行编译时提示找不到@components下的模块。

**重现**  
重现步骤
1. 使用lerna创建packages下一个工作区
2. 使用vue-cli v3.x生成的ts工程，编译选项moduleResolution设置为node
3. 引入3.0.0-alpha.9版本的we-vue
4. `npm run serve`执行编译时提示找不到@components下的模块

**预期结果**  
能够在编译选项moduleResolution设置为node时顺利通过编译。

**截图或代码** 

tyconfig配置：

  1 {                                                
  2   "compilerOptions": {                           
  3     "target": "esnext",                          
  4     "module": "esnext",                          
  5     "strict": true,                              
  6     "jsx": "preserve",                           
  7     "importHelpers": true,                       
  8     "moduleResolution": "node",                  
  9     "experimentalDecorators": true,              
 10     "esModuleInterop": true,                     
 11     "allowSyntheticDefaultImports": true,        
 12     "sourceMap": true,                           
 13     "baseUrl": ".",                              
 14     "types": [                                   
 15       "webpack-env",                             
 16       "mocha",                                   
 17       "chai"                                     
 18     ],                                           
 19     "paths": {;234m                              
 20       "@/*": [                                   
 21         "src/*"                                  
 22       ]                                          
 23     },                                           
 24     "lib": [                                     
 25       "esnext",                                  
 26       "dom",                                     
 27       "dom.iterable",                            
 28       "scripthost"                               
 29     ]                                            
 30   },                                             
 31   "include": [                                   
 32     "src/**/*.ts",                               
 33     "src/**/*.tsx",                              
 34     "src/**/*.vue",                              
 35     "tests/**/*.ts",                             
 36     "tests/**/*.tsx"                             
 37   ],                                             
 38   "exclude": [                                   
 39     "node_modules"                               
 40   ]                                              
 41 }                                                

编译报错：
 ERROR  Failed to compile with 2 errors                                                                                                                                                                                              2:40:02 PM

These dependencies were not found:

* we-vue/lib/button in ./src/main.ts
* we-vue/lib/we-vue.css in ./src/main.ts

To install them, you can run: npm install --save we-vue/lib/button we-vue/lib/we-vue.css
Type checking in progress...
ERROR in /home/q/dev/github/yimiwan/packages/webapps/node_modules/we-vue/types/lib.d.ts
12:27 Cannot find module '@components/WDialog'.
    10 |   }
    11 |
  > 12 |   import { WDialog } from '@components/WDialog'
       |                           ^
    13 |   import { WToast } from '@components/WToast'
    14 |   import { WTopTips } from '@components/WTopTips'
    15 |
ERROR in /home/q/dev/github/yimiwan/packages/webapps/node_modules/we-vue/types/lib.d.ts
13:26 Cannot find module '@components/WToast'.
    11 |
    12 |   import { WDialog } from '@components/WDialog'
  > 13 |   import { WToast } from '@components/WToast'
       |                          ^
    14 |   import { WTopTips } from '@components/WTopTips'
    15 |
    16 |   const WActionsheet: Component
ERROR in /home/q/dev/github/yimiwan/packages/webapps/node_modules/we-vue/types/lib.d.ts
14:28 Cannot find module '@components/WTopTips'.
    12 |   import { WDialog } from '@components/WDialog'
    13 |   import { WToast } from '@components/WToast'
  > 14 |   import { WTopTips } from '@components/WTopTips'
       |                            ^
    15 |
    16 |   const WActionsheet: Component
    17 |   const WAreaPicker: Component
ERROR in /home/q/dev/github/yimiwan/packages/webapps/src/main.ts
3:10 Module '"../node_modules/we-vue/types"' has no exported member 'Button'.
    1 | import Vue from "vue";
    2 | // import WeVue from 'we-vue'
  > 3 | import { Button } from 'we-vue'
      |          ^
    4 |
    5 | import 'we-vue/lib/we-vue.css'
    6 |
Version: typescript 3.4.3
Time: 4643ms

**Comment by tianyong90** [comment]
3.0.0-alpha.12 中修复
