### ISSUE TITLE
 datetime-picker 报  Cannot read property 'getFullYear' of undefined 错误

### ISSUE THREAD

**Issue by mengdream** [tianyong90/we-vue#11]
## 我用的环境

OS: Mac OS 10.12.6
浏览器： Chrome Version 60.0.3112.101 (Official Build) (64-bit)
webpack 版本：2.7.0
we-vue 版本：1.4.9

## 问题及现象
使用官方的 Example 中的 datetime-picker.vue，报错

`[Vue warn]: Error in getter for watcher "rims": "TypeError: Cannot read property 'getFullYear' of undefined"`
![screen_shot_2017-08-24_at_3_38_25_pm](https://user-images.githubusercontent.com/3888694/29655229-e030c980-88e2-11e7-8ef1-4612d5784195.jpg)

<img width="730" alt="screen shot 2017-08-24 at 3 37 24 pm" src="https://user-images.githubusercontent.com/3888694/29655036-274cac90-88e2-11e7-89af-29f68b8ecb6f.png">

**Comment by tianyong90** [comment]
v1.4.11 中修正。

**Comment by wsygdiv** [comment]
现在还是有这个问题
![image](https://user-images.githubusercontent.com/26573456/35374178-c02a1664-01dc-11e8-8a38-f941215790a3.png)

**Comment by tianyong90** [comment]
确定安装的是最新稳定版本？ v1.6.2

**Comment by wsygdiv** [comment]
最近才用的，不超过三星期吧

**Comment by tianyong90** [comment]
方便的话，贴你下你的代码。或者自己参考 v1 分支里，对应的示例源码检查下看。

**Comment by wsygdiv** [comment]
<span class="edit-more" size="large" @click="open('picker4')"><span class="btn-right iconfont"><span class="info-private"v-text="birthday"></span>&#xe602;</span>
					</span>

<mt-datetime-picker ref="picker4":startDate="startDate":endDate="endDate" type="date" v-model="birthday" year-format="{value} 年" month-format="{value} 月" date-format="{value} 日"@confirm="handleChange">
		</mt-datetime-picker>

**Comment by wsygdiv** [comment]
代码较多，只贴这部分

**Comment by tianyong90** [comment]
我这里的，应该是 <wv-datetime-picker> 啊，虽然也说过是参考的 mint-ui 但还是有不少改动。确定是用的我的包并看的我的文档？ 😈

**Comment by wsygdiv** [comment]
我用的是mint-ui,不一样吗

**Comment by tianyong90** [comment]
不一样啊，用它的就看它的文档吧。我这个并不是单纯的 fork，而是参考，并根据情况作了不少修改。

**Comment by wsygdiv** [comment]
那
![image](https://user-images.githubusercontent.com/26573456/35375296-85ea408c-01e1-11e8-8102-627a3dd0ec2a.png)这个格式怎么转成正确的格式

**Comment by tianyong90** [comment]
picker 取到的值是一个 Date 对象，根据自己需要转就是了。可以去看官方示例或文档，mint-ui 也是开源的。

**Comment by wsygdiv** [comment]
嗯，自己转了一下
