### ISSUE TITLE
文档问题， swipe多了一个=运算符

### ISSUE THREAD

**Issue by deepkolos** [tianyong90/we-vue#110]
**环境信息:**
 - 设备: [e.g. iPhone6]
 - 浏览器： [e.g. chfome]
 - we-vue 版本： [e.g. v3.0.0]
 - 包管理工具： [npm/yarn]
 - Node.js 版本：

**Bug 描述**  
简要描述 BUG

**重现**  
重现步骤

**预期结果**  
描述预期得到的结果

**截图或代码** 
贴上截图或者相关使用代码，能更清楚的说明问题。

![image](https://user-images.githubusercontent.com/12824616/56471859-de09eb80-6489-11e9-8d18-14629d4955c9.png)

**Comment by tianyong90** [comment]
谢谢反馈，稍后修复！
