### ISSUE TITLE
关于表单提交

### ISSUE THREAD

**Issue by new-wang** [tianyong90/we-vue#117]
<wv-group title="带验证">
  <wv-input label="请输入 abc" placeholder="请输入 abc" v-model="valueText" pattern="^abc$" :validate-mode="{onFocus: false}"></wv-input>
  <wv-input label="必填字段" placeholder="请输入内容" v-model="valueRequired" required></wv-input>
  <wv-input label="失焦时验证" placeholder="请输入内容" v-model="valueOnBlur" required :validate-mode="{onFocus: false, onBlur: true, onChange: false}"></wv-input>
</wv-group>

input没有一个统一的提交验证啊

**Comment by tianyong90** [comment]
目前的设计没有，因为 input 都是独立的，没有包在 form 中。
