### ISSUE TITLE
请问FormPreview组件的按钮事件如何获得该行的数据？

### ISSUE THREAD

**Issue by kiwiflydream** [tianyong90/we-vue#118]
![image](https://user-images.githubusercontent.com/13311001/59984335-8c353b80-965b-11e9-870f-86bff315c926.png)
```json
buttons1: [
        {
          text: '操作',
          type: 'primary',
          action: function () {
            console.log('执行主要操作……')
          }
        }
      ]
```
这个 function 有可用形参吗？

**Comment by tianyong90** [comment]
没有形参。数据可以用组件绑定的就好了，比如 `this.formData`，而这个 formData 是 formPriview 里显示的那些项的数据源。另外根据自己的情况选择使用 function () 或是箭头函数。

**Comment by kiwiflydream** [comment]
> 没有形参。数据可以用组件绑定的就好了，比如 `this.formData`，而这个 formData 是 formPriview 里显示的那些项的数据源。另外根据自己的情况选择使用 function () 或是箭头函数。

好的，谢谢大佬
