### ISSUE TITLE
media-box 中的 title，希望使用 v-html 绑定

### ISSUE THREAD

**Issue by musez** [tianyong90/we-vue#122]
希望 media-box 中的 title 能和 cell 中的 title 一样，使用 v-html 指令
![image](https://user-images.githubusercontent.com/14009673/60864586-927c0800-a256-11e9-9e5a-714d03c069d8.png)

![image](https://user-images.githubusercontent.com/14009673/60864478-5183f380-a256-11e9-8ac0-b6b2a14e3065.png)

**Comment by tianyong90** [comment]
@musez 非常感谢反馈，同时也欢迎 PR。:smile:
