### ISSUE TITLE
checklist 需要点击很多次才有效

### ISSUE THREAD

**Issue by deepkolos** [tianyong90/we-vue#14]
## 我用的环境

OS:
浏览器：chrome stable 61
webpack 版本：3
we-vue 版本：latest

## 问题及现象

![bug](https://user-images.githubusercontent.com/12824616/31020026-4b5975c0-a564-11e7-8e2c-353997fdd6bd.gif)

![2017-09-29_221719](https://user-images.githubusercontent.com/12824616/31020038-52fe4210-a564-11e7-93f0-97e5c31ac3b3.png)

**Comment by deepkolos** [comment]
在chrome 手机适配模式为 ip5

**Comment by tianyong90** [comment]
被动监听器引起的相关问题，虽然真机上没法重现，不过确实得作兼容性优化。
