### ISSUE TITLE
datePicker出现死循环了

### ISSUE THREAD

**Issue by deepkolos** [tianyong90/we-vue#16]
## 我用的环境

OS:windows 10
浏览器：chrome 62 stable
webpack 版本：3.5.6
we-vue 版本：1.4.12

## 问题及现象

官网的

http://wevue.org/doc/index

点进去DateTimePicker卡死了, 估计是出现了死循环, 内存占用一直上涨, 无交互响应

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

![deadloop](https://user-images.githubusercontent.com/12824616/32202808-2b468510-be1a-11e7-8ea6-c3a3f5dc5b86.png)

**Comment by tianyong90** [comment]
@deepkolos 感谢！如果方便的话更新到最新版本试下，问题重现的话，我来处理。

**Comment by deepkolos** [comment]
![2017-10-31_135034](https://user-images.githubusercontent.com/12824616/32209306-a3c73f8e-be42-11e7-8c7f-6a2e69760512.png)

**Comment by tianyong90** [comment]
已经在处理了，确实是 while 语句使用不当引起。感谢反馈！
