### ISSUE TITLE
Picker组件的change事件监听有问题

### ISSUE THREAD

**Issue by que01** [tianyong90/we-vue#2]
我认为代码应该改成这样的，代码文件是Picker.vue
`
<wv-picker-slot v-for="slot in slots" :key="slot" :values="slot.values || []" :valueKey="valueKey"
                        v-model="values[slot.valueIndex]"
                        v-on:input="slotValueChange"
                        ></wv-picker-slot>
`
也就是v-on:input="slotValueChange"这句 现在没有，然后wv-picker-slot内部的$emit('input')调用就断了
另，希望文档不仅仅是props的 ，也把事件写上，这样不用每次都翻源码。。。

**Comment by tianyong90** [comment]
如果方便，提交 PR 会不胜感激。 😄 当然，我抽空后仔细检查这部分代码的。
文档方面目前仍在不断完善中，部分文档已经加上事件的说明了，余下的会逐步补全。感谢反馈！
