### ISSUE TITLE
滚动到底部v-infinite-scroll指令无限触发

### ISSUE THREAD

**Issue by markflyfly** [tianyong90/we-vue#20]
## 我用的环境

OS:Windows
浏览器：Chrome
webpack 版本：本地引入
we-vue 版本：最新版本

## 问题及现象

![无限加载](https://user-images.githubusercontent.com/15846359/32826546-c2a9c9ca-ca23-11e7-9607-a711decad1c7.png)
代码结构
![image](https://user-images.githubusercontent.com/15846359/32826652-36fbba0e-ca24-11e7-90d5-54500d7f5add.png)

**Comment by markflyfly** [comment]
@tianyong90

**Comment by tianyong90** [comment]
使用 infinite-scroll 指令的元素，其父级元素需要有一个确定的高度，所以这里也不建议直接在 #app 结点上使用这个指令。可以去看看示例源码。https://github.com/tianyong90/we-vue/blob/master/example/pages/infinite-scroll.vue
注意里面那个 `:style="{ height: wrapperHeight + 'px' }"` 的地方

**Comment by markflyfly** [comment]
改造成如下代码结构，仍然是无限触发，
![image](https://user-images.githubusercontent.com/15846359/32828074-229436a4-ca29-11e7-9ab5-ebdb4c19e64f.png)

**Comment by tianyong90** [comment]
`infinite-scroll-disabled="loading"` 改成 `:infinite-scroll-disabled="loading"` 试试。我这一直没法重现你的问题。

**Comment by tianyong90** [comment]
@markflyfly 好的，刚刚折腾问题重现了。稍后会优化这部分。

**Comment by markflyfly** [comment]
@tianyong90 谢谢，重现很不容易哦，因为今天要发布，所以我直接全部loading 整个数据了，去除了滚动加载，下一版再加上，thanks for your work

**Comment by tianyong90** [comment]
检查了代码之后，发现 BUG 不在组件里，而出在用法上，之前的示例写法不够严谨，可能造成了误导 ......
示例的调整可见：https://github.com/tianyong90/we-vue/commit/56134003440b504c86e190f9d7aadf8f73e7601b

**Comment by markflyfly** [comment]
@tianyong90 我看看

**Comment by markflyfly** [comment]
最后提一下昨天是用的对话框组件问题， 官网的关于Dialog部分的api是否有拼写单词错误
![image](https://user-images.githubusercontent.com/15846359/32872111-e4b7f0ea-cabf-11e7-80b1-4622ceb49f10.png)
<pre>
 this.$dialog({
                    title:"提示!",
                    message:"需要更多的积分才可以兑换这个商品哦",
                    cancelText:"取消",
                    confirmText:"赚积分",
                    showConfirmBtn:true,
                    showCancelBtn:true,
                })
</pre>
只有在如上配置全部参数后才正确显示

**Comment by tianyong90** [comment]
确实是。马上更正。
