### ISSUE TITLE
请问你这个图片懒加载怎么设置默认图片

### ISSUE THREAD

**Issue by 754278241** [tianyong90/we-vue#21]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by tianyong90** [comment]
we-vue 中懒加载是封装的， [vue-lazyload](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1513754344144&di=cbf013aca4e440adab58d75ba0258c8a&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimgad%2Fpic%2Fitem%2F728da9773912b31bc2fe74138d18367adab4e17e.jpg), 更多高级的用法可以参考它的官方文档。

对于整体引入的情况，可以使用下面这种方式配置默认的配置。
```js
Vue.use(WeVue, {
  lazyload: {// yourconfig}
}
```
