### ISSUE TITLE
picker小细节~

### ISSUE THREAD

**Issue by deepkolos** [tianyong90/we-vue#22]
## 我用的环境

OS: win 10 1703
浏览器：chrome dev 63
webpack 版本：
we-vue 版本：picker分支

## 问题及现象

![we-vue-picker](https://user-images.githubusercontent.com/12824616/34330283-5d87a0e8-e955-11e7-806e-d1c12bbf3572.gif)

记得之前联动的子栏是支持异步的, 我在设置的时候才使用了task队列, 还有单位的支持~~ 

感觉高度也是可以自定义的支持, mint-ui记得值3 ,5, 7的奇数~~

可以做picker-view拆分, ant-design-mobile, vant也做了这一层的拆分, 为后续的复用提供基础~~

提个issue, 点亮github今天的contribution 😄 ~ 哈哈~

**Comment by tianyong90** [comment]
异步的会考虑按你的思路换个写法来实现，或者使用其它的机制以方便多列联动，目前还在完善中，这部分差不多是重写了，picker 和 date-picker 算是个库里代码最复杂的组件了。
这次是2.0版本的重构，作了不少调整，另外就是单元测试要覆盖至少九成以上。
