### ISSUE TITLE
大神，例子挂了

### ISSUE THREAD

**Issue by donxbei** [tianyong90/we-vue#23]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

DEMO不能看了

**Comment by tianyong90** [comment]
是指在线示例么？ 链接是 https://demo.wevue.org, 官方文档站 https://wevue.org 刚试过都访问正常。
如果是指本地开发时的预览，可否说明版本、具体报错信息？

**Comment by donxbei** [comment]
官方文档里右边的例子看不了了

**Comment by tianyong90** [comment]
已经处理好了……
抱歉，是前天配置 SSL 引起的，最近忙着重构没太注意这个站。

**Comment by donxbei** [comment]
谢谢
