### ISSUE TITLE
日期选择器里能只选到月份，天数不要的吗

### ISSUE THREAD

**Issue by donxbei** [tianyong90/we-vue#24]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by tianyong90** [comment]
https://demo.wevue.org/datetime-picker 看下这个示例，另外文档里有更详细的参数说明。 https://wevue.org。
