### ISSUE TITLE
input失去焦点事件不触发

### ISSUE THREAD

**Issue by holyedding** [tianyong90/we-vue#26]
## 我用的环境

OS:win7
浏览器：chrome
webpack 版本：2.4.1
we-vue 版本：最新

## 问题及现象
 <wv-group title="查询患者信息" >
            <wv-input label="住院号" placeholder="请输入住院号" v-model="cardno" v-on:blur="selectCardNo" required></wv-input>
            <ul class="weui-media-box__info" slot="box_ft">
                <li class="weui-media-box__info__meta" style="color: gray">{{tips}}</li><br>
            </ul>
        </wv-group>
  export default {
        name: "inp-patient-search",
        data () {
            return  {
                cardno:'',
                tips:''
            }
        },
        methods:{
           
            selectCardNo(){
                console.log(this.cardno)
                this.axios.post('api//inPatent//getInpPatientInfo',{
                    cardno: this.cardno,
                }).then((response)=> {
                    if (response.data.data.success!=='true'){
                        this.tips='住院号输入有误,请重新输入'
                    }else{
                        this.tips=''
                    }
                })
            }
        }
    }
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
input失去焦点事件不触发

**Comment by tianyong90** [comment]
可以粘贴下 input 部分的代码不？

**Comment by holyedding** [comment]
<wv-input label="住院号" placeholder="请输入住院号" v-model="cardno" @blur='selectCardNo'  required :validate-mode="{onFocus: false, onBlur: true, onChange: false}"></wv-input>,不好意思,这两天有事,没及时回复,input失去焦点之后,不会触发相关函数

**Comment by tianyong90** [comment]
感谢反馈！
之前确实考虑不周，刚刚根据这点进行了优化并发布了个新的版本 [v1.6.1](https://github.com/tianyong90/we-vue/releases/tag/v1.6.1)，可以更新一下。

**Comment by holyedding** [comment]
好的,麻烦了!
