### ISSUE TITLE
哥们，请问怎么适配移动端

### ISSUE THREAD

**Issue by wjjhhh** [tianyong90/we-vue#28]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by tianyong90** [comment]
这个库本来主要就是针对移动端、特别是微信开发的。这里说的‘适配’具体指什么？

**Comment by wjjhhh** [comment]
不好意思老哥，找到原因了，我用了flexible，scale自动缩放了，所以看起来小了

**Comment by tianyong90** [comment]
😄
