### ISSUE TITLE
demo中 picker联动 取值有错误

### ISSUE THREAD

**Issue by Simingchen** [tianyong90/we-vue#29]
## 我用的环境

OS: 
浏览器：微信
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤
市级县级这一层取到了上一层值
描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

**Comment by deepkolos** [comment]
方便贴张图片么? @Simingchen
