### ISSUE TITLE
[new feature] 支持input输入框，当失焦时才校验

### ISSUE THREAD

**Issue by pugwoo** [tianyong90/we-vue#3]
现状：当wv-input加上required属性时，页面打开即显示红色和感叹号。

**期望**

增加一个checkOnBlur:Boolean属性：当为true时，页面打开时不会提示感叹号，当用户点击该输入框后失焦，发现校验不过时，才显示感叹号。当为false时，表现和目前一致。

多谢！

**Comment by tianyong90** [comment]
这建议好啊，下一个版本加上。

**Comment by tianyong90** [comment]
实际做的时候发现，直接新增这样一个 Boolean 属性可能会与已有的 no-validate 属性引起混淆和误解，按这样的逻辑说不种还要加入 validataOnFocus ……一大堆属性，所以综合考虑了下，决定废弃原有的 no-validate 属性同时添加一个 validate-mode 属性来表示不同的验证行为模式可能会比较合适。 @pugwoo

**Comment by pugwoo** [comment]
@tianyong90 我也觉得no-validate不太清楚其意图，可能是一个总开关。我原本想先关闭验证，然后在用户失焦时开启验证，可惜失焦事件并没有抛出来。如果重新设计的话，去掉no-validate，加入validate-mode可以。

另外一个问题是，有没有可能由父组件主动focus到子组件上，并要求子组件进行验证工作，也即validate-mode有一种是手工manual，并提供手工触发的可能。我不太懂，设想一下而已。

**Comment by tianyong90** [comment]
v1.4.0版本中已实现这一需求，故关闭此 issue
