### ISSUE TITLE
picker.getValues()取不到值

### ISSUE THREAD

**Issue by yuyuabc1** [tianyong90/we-vue#30]
wv-picker(v-model="typePickerShow",:slots="typeList",value-key="name",@confirm="confirmType")
列表顺利出现了
但是使用confirm方法时 picker.getValues()[0] 取值为undefinded

## 问题、现象以及重现步骤

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

**Comment by tianyong90** [comment]
用的哪个版本？能贴下具体代码不？

**Comment by yuyuabc1** [comment]
用的1.6.2版本
我现在使用了你2.0的版本  可以正常取值

**Comment by tianyong90** [comment]
好的，2.0 版 alpha 阶段马上也要结束了，文档完善后会正式发布。我去看下 1.6 版的确认下。

**Comment by yuyuabc1** [comment]
2.0的文档和代码大概在几号发布？

**Comment by tianyong90** [comment]
官网上大部分文档已经写完了，除 picker 和 datetime-picker 部分的，还在整理，这两个组件有不小的调整，预计这周内整理完。
