### ISSUE TITLE
NumberSpinner

### ISSUE THREAD

**Issue by yuyuabc1** [tianyong90/we-vue#31]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

NumberSpinner的样式实在是太丑了  而且center并不是居中的  我忍不住吐槽下。。。

**Comment by tianyong90** [comment]
非专业前端。
其实做这个无非就是想抛砖引玉，希望大家一起完善，无奈水平和影响力都有限。
如果有更好的样式设计，欢迎 PR。
