### ISSUE TITLE
使用nuxt.js 按需加载失败

### ISSUE THREAD

**Issue by mindreading** [tianyong90/we-vue#32]
## 我用的环境

OS: Mac OS
浏览器：Chrome 64.0.3282.186 64位
webpack 版本：3.11.0
we-vue 版本：2.0.1

## 问题、现象以及重现步骤

使用相同的配置，在mint-ui上可以实现按需加载，在we-vue上无法实现按需**样式**的加载，页面无样式！
![wx20180305-164633](https://user-images.githubusercontent.com/12807738/36965622-2bf32b34-2095-11e8-8253-7eb16cf7ad4c.png)

**Comment by tianyong90** [comment]
公共部分样式需要手动载入的，也就是下面图里的这个文件。这文件中包含 weui.css, lazyload 等一些样式，没做拆分。
![image](https://user-images.githubusercontent.com/9278461/36967201-0efebb10-209a-11e8-87ce-2d7c16f6fa94.png)

**Comment by mindreading** [comment]
好吧。。。 谢谢了
