### ISSUE TITLE
InfiniteScroll组件

### ISSUE THREAD

**Issue by yuyuabc1** [tianyong90/we-vue#33]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤

为什么我没有滚动到底部也会触发   往上往下滚动 都会触发loadmore事件

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

**Comment by tianyong90** [comment]
贴下代码吧？infinite-scroll-distance 之类的属性设置多少？
