### ISSUE TITLE
调用Dialog组件  点击无反应

### ISSUE THREAD

**Issue by yuyuabc1** [tianyong90/we-vue#34]
## 我用的环境

template部分
div(class="btn-right", @click="showMethod") 计算方式

js部分
import { Dialog } from 'we-vue'
  methods: {
    showMethod () {
      console.log('1')
      Dialog({
        title: '对话框标题',
        message: 'hello world',
        skin: 'ios',
        showCancelButton: false
      })
    }
  }

调试台 显示'1'  但是Dialog没有出现

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

**Comment by tianyong90** [comment]
we-vue 用的哪个版本？
