### ISSUE TITLE
CheckList组件中 设置align属性无效

### ISSUE THREAD

**Issue by 273851541** [tianyong90/we-vue#35]
## 我用的环境

OS:Win10
浏览器：chrome
webpack 版本：3.6.0
we-vue 版本：2.0.2

## 问题、现象以及重现步骤

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

**Comment by tianyong90** [comment]
感谢反馈！已在 2.0.3 版本中修正。
