### ISSUE TITLE
2.0版本 DIalog

### ISSUE THREAD

**Issue by yuyuabc1** [tianyong90/we-vue#36]
## 我用的环境

OS:
浏览器：chrome
webpack 版本：3.10.0
we-vue 版本：2.0

## 问题、现象以及重现步骤

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

      Dialog({
        message: 'hello world',
        skin: 'ios'
      })
   使用Dialog组件 弹框不出现
   观察html元素 出现该元素 但是一直是display:none

**Comment by tianyong90** [comment]
抱歉！请更新到最新版。这个 BUG 在 v2.0.2 中修复了。

![image](https://user-images.githubusercontent.com/9278461/38024438-99d464ae-32b7-11e8-9485-1fa82da7882e.png)
