### ISSUE TITLE
iconfont issue

### ISSUE THREAD

**Issue by 1236897** [tianyong90/we-vue#39]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤

下载develop和master分支都尝试过，按照教程步骤运行了 npm install ， npm run dev后，就马上报这个错了

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。
![Uploading 图片.png…]()
 ERROR  Failed to compile with 2 errors                                                                                                                                                                 12:24:12

 error  in ./example/assets/images/icon_tabbar.png

Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/file-loader/dist/index.js:34:48)
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/url-loader/dist/index.js:61:19)

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/eslint-loader??ref--5-0!./node_modules/eslint-loader??ref--18!./example/pages/grid.vue?vue&type=script&lang=
js 55:0-58 60:18-28
 @ ./example/pages/grid.vue?vue&type=script&lang=js
 @ ./example/pages/grid.vue
 @ ./example sync ^\.\/pages.*\.vue$
 @ ./example/router/index.js
 @ ./example/main.js
 @ multi (webpack)-dev-server/client?http://IP:8080 webpack/hot/dev-server ./example/main.js

 error  in ./example/assets/iconfont/iconfont.svg?t=1505363621205

Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/file-loader/dist/index.js:34:48)
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/url-loader/dist/index.js:61:19)

 @ ./node_modules/css-loader??ref--13-1!./node_modules/postcss-loader/lib??ref--13-2!./example/assets/iconfont/iconfont.css 7:8805-8846
 @ ./example/assets/iconfont/iconfont.css
 @ ./example/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.112:8080 webpack/hot/dev-server ./example/main.js

**Comment by tianyong90** [comment]
请拉取下最新的代码，然后更新全部依赖。应该与 vue-loader 有关，因为最近更新到 vue-loader15 了，但我是用 yarn 安装的，里面的 package-lock.json 没更新，用 npm 安装的话 vue-loader 版本就可能不对。
目前决定删除 package-lock.json 以便项目维护。抱歉。
