### ISSUE TITLE
[tutorial] picker怎样做级联选择呢？

### ISSUE THREAD

**Issue by pugwoo** [tianyong90/we-vue#4]
希望学习到怎样使用picker完成下面的功能：

1. 怎样做级联选择，例如省市的选择？如果没法做到选择省份后动态去后台拉去城市列表，那么做到后台一次性全部吐出所有省市也可以。

2. 怎样动态地由父组件改变picker当前选择的值？当页面动态去后台请求数据之后，想直接定位picker到某个值上。

谢谢！

**Comment by tianyong90** [comment]
picker 组件可以设置多个 picker-slots 但具体的联动逻辑就得自己来实现了，组件内置了几个方法有于设置和获取这些 slots。这一方面后期会加入相关的示例。

**Comment by pugwoo** [comment]
@tianyong90 这个我挺外行的，期待你的示例哈

**Comment by tianyong90** [comment]
示例已完成了，可以摘取看源码。
