### ISSUE TITLE
DatetimePicker 组件无法定位到当前时间

### ISSUE THREAD

**Issue by yanwu999** [tianyong90/we-vue#41]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：2.1.1

## 问题、现象以及重现步骤
组件v-model绑定了当前日期对象，调用该组件后显示的日期时间不对，在we-vue 版本1.6.0上面是正常的,
##问题截图
![image](https://user-images.githubusercontent.com/35087563/39909656-4cbbdefe-5526-11e8-9b10-cabda657d56f.png)
![image](https://user-images.githubusercontent.com/35087563/39909670-5f9a0f28-5526-11e8-8878-52f4a2ae6b9b.png)
##期望结果
![image](https://user-images.githubusercontent.com/35087563/39909732-adeb49d0-5526-11e8-948e-68b23b4a54f9.png)

**Comment by tianyong90** [comment]
我稍后检查下。感谢反馈！

**Comment by tianyong90** [comment]
仔细检查了下代码，发现是使用方法问题。
v2 中，v-model 绑定的是当前时间值，而 picker 是否弹出显示则由 visible 属性控制（通常是 `:visible.sync=someValue`，或者使用 open() 方法。建议看下示例里的代码。

**Comment by yanwu999** [comment]
我想表达的不是弹窗显示的问题，而是调用该组件后显示的日期不对，比如传一个 new Date('2018-5-14')日期对象给组件，调用open方法打开组件后显示的日期是2008-1-1，正确的行为应该显示2018-5-14

**Comment by tianyong90** [comment]
我说的重点出不是弹出显示问题。而是 v-model 绑定的值含义在 v2 里有变化……
