### ISSUE TITLE
toast类型为text的时候没有垂直居中，怎么解决

### ISSUE THREAD

**Issue by GreatLiyi** [tianyong90/we-vue#43]
## 我用的环境

OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤

描述问题现象，报错**贴截图**粘贴或者贴具体信息，提供**相关的代码段**，说明问题重现步骤。

**Comment by tianyong90** [comment]
其实所有样式都可以通过息的样式进行覆盖的。当然，既然反馈了这个问题我会优化下。或者，非常欢迎 PR 😄
