### ISSUE TITLE
wv-picker 官网的例子报错

### ISSUE THREAD

**Issue by machuxin** [tianyong90/we-vue#45]
vue.esm.js?efeb:591 [Vue warn]: Missing required prop: "columns"

**Comment by tianyong90** [comment]
这错误提示很明显了，有个属性 columns 没值。

**Comment by machuxin** [comment]
官网的API 是 slots 属性  demo 给的是columns属性 两个属性不一致

**Comment by tianyong90** [comment]
2.x 的版本属性名改了，现在官网的文档分 1.6 和 2.0 两版本，示例也只是针对最新的版本的，所以请根据自己用的版本查看文档。升级到2.0 的时候考虑到属性语义的合理性，作了一些调整。

**Comment by machuxin** [comment]
OK 谢谢 @tianyong90

**Comment by tianyong90** [comment]
😄
