### ISSUE TITLE
图标在iOS手机端无法显示

### ISSUE THREAD

**Issue by mengdream** [tianyong90/we-vue#46]
## 我用的环境

OS:
浏览器：Safari Mobile iOS 11.3.1
webpack 版本：3.10.0
we-vue 版本：2.0.4

## 问题、现象以及重现步骤
在 Mac 端的 Chrome 和 Safari 均能显示图标，但是到了 iOS 的手机端，图标变成了方框，无法显示。代码没有变化。
![image](https://user-images.githubusercontent.com/3888694/40578158-f50048e4-6141-11e8-9961-06fb39293e8e.png)

手机端显示的图标是一个方框
![image](https://user-images.githubusercontent.com/3888694/40578176-392ea696-6142-11e8-9727-380771f0837c.png)

`import Vue from 'vue';`
`import axios from 'axios';`
`import VueAxios from 'vue-axios';`
`import VueRoute from 'vue-router';`
`import App from './Crm.vue';`
`import List from './crm/List.vue';`
`import {Group, Cell, SearchBar, InfiniteScroll, Icon, Spinner, Button} from 'we-vue';`
`import 'we-vue/lib/style.css';`
`import VoerroTagsInput from './crm/VoerroTagsInput.vue';`

`Vue.use(VueAxios, axios);`
`Vue.use(VueRoute);`
`Vue.use(Group);`
`Vue.use(Cell);`
`Vue.use(SearchBar);`
`Vue.use(InfiniteScroll);`
`Vue.use(Icon);`
`Vue.use(Spinner);`
`Vue.use(Button);`

`<div id="app">`
`       ...`
`        <wv-search-bar :autofocus="false" v-model="searchString" :result="searchName"></wv-search-bar>`
`      ...`
`</div>`

**Comment by tianyong90** [comment]
更新到最新版本吧 2.1.x 版的，刚用自己手机试了下，微信内置浏览器以及 Safari 里是正常的，也可以先用手机试下在线示例的情况，在线示例都是针对最新版本的。如果发现还有问题，请再反馈下。
在线示例地址： https://demo.wevue.org

**Comment by mengdream** [comment]
手机测试在线示例是没有问题的，可以正常显示图标。

把 node_modules 文件夹删除重新安装，更新到最新的 2.1.2 的版本，问题还是存在。 

会不会我使用的是  laravel-mix 来编译的的关系？

package.json
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {},
  "dependencies": {
    "@voerro/vue-tagsinput": "^1.5.2",
    "axios": "^0.18.0",
    "bootstrap": "^4.1.1",
    "cross-env": "^5.1.6",
    "echarts": "^3.8.5",
    "element-ui": "^2.3.9",
    "jquery": "^3.3.1",
    "laravel-mix": "^2.1.11",
    "lodash": "^4.17.10",
    "popper.js": "^1.14.3",
    "vue": "^2.5.16",
    "vue-axios": "^2.1.1",
    "vue-fullcalendar": "^1.0.9",
    "vue-loader": "^14.2.2",
    "vue-router": "^3.0.1",
    "vue2-slot-calendar": "^2.1.4",
    "we-vue": "^2.1.2",
    "weui": "^1.1.2"
  }

**Comment by tianyong90** [comment]
待我明天上机试着重现下，之前也在 laravel 中用过，但不确定是否有这问题。再次感谢反馈！

**Comment by mengdream** [comment]
问题原因找到了，是我在nginx设置https里面限制了对于图片资源的获取，把这句话注释掉就可以了，非常感谢！
`add_header               Content-Security-Policy "default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' blob: https:; img-src data: https: http://ip.qgy18.com; style-src 'unsafe-inline' https:; child-src https:; connect-src 'self' https://translate.googleapis.com; ";`

**Comment by mengdream** [comment]
由于这个是企业微信上面的页面，使用了 OAuth，所以在本地调试的时候没有用到 https。后来再到放到运行环境中调试（不开启 OAuth）就能发现问题所在了。

![image](https://user-images.githubusercontent.com/3888694/40711108-f5b94e6e-642c-11e8-90d0-85dcd671b419.png)

图标是字体文件，在 Content-Security-Policy 规则里面加上一条：
`font-src data: `
问题就解决了。

毕竟 https 加上 Content-Security-Policy 是为了网站安全 😀

**Comment by tianyong90** [comment]
非常感谢！稍后我把这整理到在线文档里去。 😃

**Comment by mengdream** [comment]
好的好的，使用上面有问题再来请教 😀

**Comment by lai1245199086** [comment]
Toast加载中，如何遮罩，是当前页面无法被点击
