### ISSUE TITLE
infinite-scroll 跨页面屏幕滚动仍旧触发数据加载

### ISSUE THREAD

**Issue by mengdream** [tianyong90/we-vue#47]
## 我用的环境
OS:Mac
浏览器：Chrome 66.0.3389.181
webpack 版本：3.11.10
we-vue 版本：2.1.2
vue-router 版本 3.0.1

## 问题、现象以及重现步骤
录屏动画如下
![we-vue infinite-scroll](https://user-images.githubusercontent.com/3888694/40766290-965181b6-64e1-11e8-9194-6ddc69665cda.gif)

按照示例代码，在 wv-group 里面使用 infinite-scroll，内含 wv-cell 列表项，并且带跳转。问题是跳转到新的页面后（使用 vue-router），仍旧会触发原有页面内的 loadMore 方法，造成数据的重复加载。

代码如下：
![image](https://user-images.githubusercontent.com/3888694/40768543-330bc484-64e8-11e8-9aee-ccbf1769372e.png)
![image](https://user-images.githubusercontent.com/3888694/40768557-3fe77cac-64e8-11e8-9e91-5cf74dff2651.png)
![image](https://user-images.githubusercontent.com/3888694/40768579-53db0346-64e8-11e8-8c78-8393722b23e6.png)

**Comment by tianyong90** [comment]
感谢反馈！正在设法重现调试……

**Comment by tianyong90** [comment]
确实是事件监听器方面没有适当销毁引起。待修正后发下一个版本。

**Comment by mengdream** [comment]
好的，期待新版本。
