### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by Xiangfs** [tianyong90/we-vue#50]
在线文档上面，在actionsheet里面，对actions的配置完全没有啊，希望能完善一下，关于actions里面的回调选择后回调啊之类的。
摸索之后才发现数组内写method会被调用到，但是方法内部没法拿到当前vue的实例对象，this指的是当前数组对象本身，没法去改变vue实例下的data内的数据。

**Comment by tianyong90** [comment]
感谢提醒，稍后去完善下！
