### ISSUE TITLE
Navbar 只有样式，下方内容怎么切换啊？

### ISSUE THREAD

**Issue by machuxin** [tianyong90/we-vue#51]
div的切换方式，是自己写js？？？？

**Comment by tianyong90** [comment]
目前设计的是，用户自己实现内容切换，不管是用 router-view，条件渲染还是直接跳转都可以实现的。

不过也正计划新增一个 tab-container 性质的组件，用于与 tabbar 和 navbar 配合使用。

**Comment by machuxin** [comment]
好的好的，谢谢

**Comment by tianyong90** [comment]
2.2.0 版本开始加入 tabs 组件，替代现有的 navbar 组件。navbar 组件功能比较简陋，计划在后续版本中废弃。
