### ISSUE TITLE
wv-datetime-picker使用遇到的问题

### ISSUE THREAD

**Issue by q154494562** [tianyong90/we-vue#53]
## 我用的环境

OS:
浏览器：谷歌
webpack 版本：3.6.0
we-vue 版本：2.5.2

## 问题、现象以及重现步骤

1、使用时间选择器wv-datetime-picker组件时，v-model=“这里应该传字符串还是数字？还是new Date()”？
2、我使用了该组件为什么height为0不显示呢？

**Comment by Ritr** [comment]
<wv-datetime-picker        
        ref="picker"
        type="datetime"
        cancelText=""      
        startDate = new Date()  
        >
    </wv-datetime-picker>

提示我传的startDate是string类型，不是date类型，请问该如何解决

**Comment by tianyong90** [comment]
兄弟可能需要再仔细看一下 vue 的文档，html 里用的属性一般是 kebab-case 而组件属性名定义的时候用的是 camelCase。

也就是说，应该是 `:start-date="new Date()"`

另外也可以看下在线实例的源码……

**Comment by JCL666** [comment]
DatetimePicker 在线示例，手机和PC端日期选择点击都没有反应,第一次用这个组件,也不清楚什么原因，望大神指教。
