### ISSUE TITLE
Datetimepicker时间选择器 遇到的问题

### ISSUE THREAD

**Issue by Roo1ke** [tianyong90/we-vue#59]
## 我用的环境

OS:win 7
浏览器：chrome
webpack 版本：
we-vue 版本：2.1.2

当使用时间选择器时，手动给datetimepicker赋值，当赋值时间是小于10点时，无法成功改变datetimepicker的选中项

![tim 20180723101552](https://user-images.githubusercontent.com/32088992/43053846-6772fd6c-8e61-11e8-914b-928c27660c64.png)

![tim 20180723101719](https://user-images.githubusercontent.com/32088992/43053906-b26db8ca-8e61-11e8-890d-b8c3ea51d64b.png)
![tim 20180723101843](https://user-images.githubusercontent.com/32088992/43053927-cd02ec14-8e61-11e8-9356-852bc91ef82b.png)
但是当赋值时间>=10点时，可以成功改变选中项
![tim 20180723102031](https://user-images.githubusercontent.com/32088992/43053991-16cc246e-8e62-11e8-8b97-0354262ec1ed.png)
不知道是不是自己的使用方法有问题，希望得到作者的指点，

**Comment by tianyong90** [comment]
感谢反馈，确定是个 BUG。已经修正并发布发新版本 2.1.5，请更新下。
