### ISSUE TITLE
wv-input 组件如何让input输入框聚焦

### ISSUE THREAD

**Issue by markflyfly** [tianyong90/we-vue#6]
典型使用场景：当我选择发送验证码时，验证码发送成功后需要自动让验证码的输入框聚焦，这样可以提高一点用户体验
现状：在wv-input的设置id或class时，该值会被设置在最外层包裹的div中，实际上期望应该是直接设置在input标签上，然后发送验证码成功时执行document.getElementById('myInput').focus()使输入框聚焦，在不使用jquery的情况下较难选择到输入框并聚焦

**Comment by markflyfly** [comment]
@tianyong90

**Comment by tianyong90** [comment]
在 vue 里一般使用 $refs、$children 等属性来指定要操作的部分。
刚刚针对这条 issue 进行了调整，input 作了小调整并发了个新版本 [v1.4.4](https://github.com/tianyong90/we-vue/releases/tag/v1.4.4)

具体使用方法如下：
```js
<wv-input label="label" ref="theInput"></wv-input>

this.$refs.theInput.focus() 

// 或者更原始粗暴一点儿
this.$refs.theInput.$refs.input.focus()
```

**Comment by markflyfly** [comment]
@tianyong90 thanks
