### ISSUE TITLE
如何和其它组件库混合使用按需加载，增加到babel后引用样式没有生效

### ISSUE THREAD

**Issue by Kennersky** [tianyong90/we-vue#62]
## 我用的环境
vue cli 3.0
OS:
浏览器：
webpack 版本：4.15.1
we-vue 版本：2.1.6

## 问题、现象以及重现步骤
babel.config.js配置如下
`
module.exports = {
  presets: [
    '@vue/app'
  ],
  plugins:[
	  [
	  	"import",
	  	{
		      "libraryName": "vant",
		      "libraryDirectory": "es",
		      "style": true
			}
	  ],
	  [
	  	"import",
	  	{
		      "libraryName": "we-vue",
		      "style": "style.css"
			},
			"we-vue"
	  ]
  ]
}
`

这样配置编译成功了，但是引入后，样式并没有生效，是哪里设置的问题吗？
`
import Vue from 'vue'
import { Dialog } from 'we-vue'
Vue.use(Dialog)

Dialog({
	 title: '提示',
	 message: '项目不存在!!!',
	 skin: 'ios'
});

`

![tim 20180816144112](https://user-images.githubusercontent.com/2129521/44192669-ea071600-a162-11e8-9572-99304d79b694.png)

**Comment by tianyong90** [comment]
配置里面的 `we-vue-import` 是什么？

**Comment by tianyong90** [comment]
style.css 这个是为了兼容自动加载。可以贴一下上面提到的报错信息不？

**Comment by tianyong90** [comment]
@Kennersky 刚反应过来。应该是你没有引用 css 引起的。按需加载的情况下也得引入 lib/style.css。文档里漏了这点儿，实在抱歉！

**Comment by Kennersky** [comment]
@tianyong90 好的。
