### ISSUE TITLE
没有prompt这种弹出层么？

### ISSUE THREAD

**Issue by jpz966906738** [tianyong90/we-vue#64]
没有prompt这种弹出层么？使用场景:点击修改按钮弹出层输入修改内容，获取输入的内容，请求API，关闭弹出层

**Comment by tianyong90** [comment]
暂时没做这个，不过这想法可以考虑加入需求清单。另外，可以使用 popup，input，button 等几个组件组合应该能满足基本上的功能。只不过样式上可能有些出入。
