### ISSUE TITLE
弹出toast时候，被toast覆盖的表单控件里面的分割线会不停的闪烁（android）

### ISSUE THREAD

**Issue by bfu99** [tianyong90/we-vue#67]
经过排除，发现是因为.weui-cells样式里面的伪类:before 和 :after 导致，我暂时的解决办法是把伪类的样式opacity设置为0 ， 重新写样式实现边框线条

**Comment by tianyong90** [comment]
有兴趣的话欢迎提交 PP 😄

**Comment by tianyong90** [comment]
我稍后调试下，如果无法解决，去掉动画也能算是没办法的办法了。

**Comment by tianyong90** [comment]
@bfu99 发现是 toast 组件里多了一层不必要的 div 引起的，去掉了这层，不再闪了。
https://github.com/tianyong90/we-vue/blob/master/src/components/toast/toast.vue#L3
