### ISSUE TITLE
laravel 中用的时候，Dialog 组件中有个参数confirm-text,短横线打包失败

### ISSUE THREAD

**Issue by kerwin-cn** [tianyong90/we-vue#7]
打包错误：
Syntax Error: Unexpected token, expected , (68:29)

  66 |                       message: res.data,
  67 |                       skin: 'ios',
> 68 |                       confirm-text:'哈哈',
        |                                     ^
  69 |                   })
  70 |               }
  71 |             })

 @ ./resources/assets/js/components/pages/Login.vue 8:2-235
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

不如驼峰或者下划线

**Comment by tianyong90** [comment]
贴一下你那部分的代码吧。

**Comment by kerwin-cn** [comment]
methods: {

        login () {

            var self=this;
            self.$indicator.open('提交中...');

            axios.post('/login',{
              phone:this.phone,
              password:this.password,
              remember:this.remember
            })
            .then(function(res){
                self.$indicator.close();
              if (res.data=='ok'){
                  self.$dialog({
                      title: '登录成功',
                      message: '登录成功！跳转中...',
                      skin: 'ios',
                      show-cacel-btn:false
                  });

                window.location.href='/help';
              }else{
                  self.$dialog({
                      title: '请求失败',
                      message: res.data,
                      skin: 'ios',
                      show-cacel-btn:false
                  });
              }
            })
            .catch(function(err){
              console.log(err);
            });

        },

  },

**Comment by tianyong90** [comment]
@kerwin-cn 可能你需要看一下这部分的文档。
https://cn.vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case

show-canel-btn 当在 script 里使用的时候应该使用驼峰形式，而连词符形式的用于 templete 中，大概是我的文档写得不够明确，我稍后编辑下文档去。

**Comment by kerwin-cn** [comment]
非常感谢，归根结底还是我基础不好，感谢您做了这么好的框架，会一直支持下去！

**Comment by tianyong90** [comment]
@kervin-cn :smile:

**Comment by tianyong90** [comment]
@kerwin-cn :smile:
