### ISSUE TITLE
tabbar在手机端页面放大时，不能贴紧底部的问题

### ISSUE THREAD

**Issue by lxinhcn** [tianyong90/we-vue#76]
tabbar在PC端页面放大时，可以贴紧底部，但在手机端页面放大时，不能贴紧底部，而是高出一块，不知何故？

**Comment by tianyong90** [comment]
对于移动端，比较推荐的做法是，html 中设置 viewport 指定初始缩放比例为 1 并禁用缩放的。想问下，使用过程中有这方面的设置么？
