### ISSUE TITLE
karma + mocha + chrome + webpack4

### ISSUE THREAD

**Issue by fontEndEasy** [tianyong90/we-vue#78]
请教一下如何做karma + mocha + chrome+webpack4的单元测试配置？

**Comment by tianyong90** [comment]
vue-cli 里面有针对 webpack 的模板，安装的时候可以选择用 karma + mocha 测试，只不过它默认用的是 PhantomJS，自己安装对就的 launcher 然后修改 karma.conf.js 就可以了。
另外，we-vue 1.x 版本是用的 karma+ mocha + chrome 做单元测试的，可以切到 v1 分支上去看看。

**Comment by 1515775474** [comment]
karma.conf.js在webpack4的时候，覆盖率有问题，要么都是百分百，要么覆盖率是基于编译打包后的文件的显示，但是在webpack3就没问题

**Comment by 1515775474** [comment]
karma.conf.js在webpack4的时候，覆盖率有问题，要么都是百分百，要么覆盖率是基于编译打包后的文件的显示，但是在webpack3就没问题

**Comment by fontEndEasy** [comment]
karma.conf.js在webpack4的时候，覆盖率有问题，要么都是百分百，要么覆盖率是基于编译打包后的文件的显示，但是在webpack3就没问题
