### ISSUE TITLE
header 组件的 z-index值偏低，浮动时有时会跑到其他组件下边去

### ISSUE THREAD

**Issue by kerwin-cn** [tianyong90/we-vue#8]
如题

**Comment by tianyong90** [comment]
@kerwin-cn 感谢反馈，稍后调整。

**Comment by tianyong90** [comment]
@kerwin-cn 已经作了调整并发布了新版本，见 https://github.com/tianyong90/we-vue/releases/tag/v1.4.6

如果仍然被遮挡，建议自己为 header 设置更高的 z-index 值。
