### ISSUE TITLE
Dialog 在IOS端会有层级问题 ？

### ISSUE THREAD

**Issue by BH-GeGe** [tianyong90/we-vue#80]

**Comment by BH-GeGe** [comment]
我解决了，发现是body的高度没有达到屏幕的高度然后点击Dialog的时候body高度以下的部分就会闪一下遮住 Dialog 遮罩层，我给body高度设置为屏幕的高度就没有这个问题了。

**Comment by tianyong90** [comment]
@BH-GeGe 👍
