### ISSUE TITLE
添加了tabbar,body超出屏幕高度

### ISSUE THREAD

**Issue by NormanQing** [tianyong90/we-vue#81]
添加了tabbar,body超出屏幕高度,tabbar没有固定在底部，要做么做滑动呢？

**Comment by tianyong90** [comment]
它有个·fixed`属性，设置为 true 就是固定的了。

**Comment by NormanQing** [comment]
> 它有个`fixed`属性，设置为 true 就是固定的了。

底部是固定了，但是内容区域看不全呢？有几条数据被这个底部挡住了

**Comment by tianyong90** [comment]
@NormanQing 为自己的 body 或者那个内容区设置 padding 或者 margin，根据自己情况调整就好了。tabbar 是个组件，不太可能让它去决定其它部分的样式的。

**Comment by tianyong90** [comment]
😄
