### ISSUE TITLE
Dialog 按需引入 BUG

### ISSUE THREAD

**Issue by jonnyshao** [tianyong90/we-vue#82]
Dialog组件会自动触发弹出，并且会停此当前组件的渲染

**Comment by tianyong90** [comment]
方便贴下代码不？顺便说明下使用的版本。

**Comment by jonnyshao** [comment]
`import Vue from 'vue'
import { Dialog } from 'we-vue'
Vue.use(Dialog)
Vue.prototype.$dialog = Dialog
`
项目一启动 这个Dialog 组件就会弹出来，我自己当前组件不渲染

**Comment by tianyong90** [comment]
@jonnyshao 不好意思啊，没注意到有新的回复。不过我这没法重现啊。
