### ISSUE TITLE
actionsheet选项没有回调函数吗？怎么拿到点击的值

### ISSUE THREAD

**Issue by tj610** [tianyong90/we-vue#83]
actionsheet选项没有回调函数吗？怎么拿到点击的值

**Comment by tianyong90** [comment]
actionsheet 是弹出菜单项啊，所以它的用法是，点击一个菜单后进行一些操作。每个菜单项都可以有不同的处理函数。当然，也可以用同一处理函数，通过转参数来确定是哪个菜单项被点击。

**Comment by tj610** [comment]
点击菜单项的函数怎么触发呢，求教？

**Comment by tianyong90** [comment]
https://wevue.org/doc/v2_0/action_sheet
文档里写的有，拉到最下面。

**Comment by tj610** [comment]
看到了，之前看的时候页面没刷出来底下示例代码部分，可能网络问题，感谢！

**Comment by tianyong90** [comment]
😄
