### ISSUE TITLE
地址三级联动

### ISSUE THREAD

**Issue by tj610** [tianyong90/we-vue#84]
全局引用，使用<wv-area>提示没有注册，怎么解决呢，想做地址三级联动

**Comment by tianyong90** [comment]
怎么引用的？贴下代码吧。

**Comment by tj610** [comment]
import Vue from 'vue'
import App from './App'
import router from './router'
import WeVue from 'we-vue'
import utils from './assets/js/utils.js'

import 'we-vue/lib/style.css'
import './assets/css/style.css'
import './assets/js/app.js'

Vue.use(WeVue)

Vue.prototype.$utils = utils

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})

**Comment by tj610** [comment]
别的都正常，只有wv-area会提示没有注册

**Comment by tianyong90** [comment]
@tj610 area 还在内测开发中。文档里没有的啊。

**Comment by tj610** [comment]
哦，我在demo的源码中看到area这个组件，那地址联动使用哪个组件呢，picker里面我看没有地址联动的示例代码

**Comment by tianyong90** [comment]
https://github.com/tianyong90/we-vue/blob/e0861e8846/example/pages/picker.vue
可以用 picker 实现，可以看这部分里的代码。

**Comment by tj610** [comment]
好的，感谢！
