### ISSUE TITLE
search-bar组件的cancel方法触发不了？

### ISSUE THREAD

**Issue by tj610** [tianyong90/we-vue#85]
<wv-search-bar placeholder="搜索" v-model="searchVal" @search="onSearch" @cancel="onCancel" />

**Comment by tianyong90** [comment]
可以的啊。用的哪个版本？

**Comment by tj610** [comment]
"we-vue": "^2.2.5"

**Comment by tj610** [comment]
search是没问题的，cancel触发不了

**Comment by tianyong90** [comment]
尝试下 .prevent .native 等修饰符。另外看下控制台点击 cancel 时是否有报错信息，用 vue dev-tools 看看事件触发记录是否正常。

**Comment by tj610** [comment]
都是正常的。控制台和devtools都没有报错，点击后取消按钮本身自己的隐藏都没问题，就是我自己定义的onCancel方法并没有执行。

**Comment by tianyong90** [comment]
@tj610 稍后我检查下重新发版吧。

**Comment by tianyong90** [comment]
请更新到 v2.2.7
