### ISSUE TITLE
picke多级显示获取值错误

### ISSUE THREAD

**Issue by Chang1ng** [tianyong90/we-vue#87]
![image](https://user-images.githubusercontent.com/6593784/49359866-632a7900-f712-11e8-9943-f375e58fda45.png)
代码取值如下：
![image](https://user-images.githubusercontent.com/6593784/49359898-7d645700-f712-11e8-9176-73299f945bd4.png)
二级取值始终是上一个父级选项的子集。

**Comment by tianyong90** [comment]
使用 picker.getValues() 是否能正常取得值呢？

**Comment by Chang1ng** [comment]
> 使用 picker.getValues() 是否能正常取得值呢？

可以去到，我看了下和setColumnValues()方法有关，这个方法会修改二级选项联动。
是使用demo还有啥需要添加的吗

**Comment by tianyong90** [comment]
demo 只是参考，有些场景可能要根据实际情况调整了。取当前 picker 选定值的话，用 picker.getValues() 比较规范。下个版本里会优化 picker 部分，并把地址联动选择分离成一个组件。

**Comment by Chang1ng** [comment]
> demo 只是参考，有些场景可能要根据实际情况调整了。取当前 picker 选定值的话，用 picker.getValues() 比较规范。下个版本里会优化 picker 部分，并把地址联动选择分离成一个组件。

试了试所有可用的钩子方法。
找到一种笨方法。
通过getColumnValue(index)方法获取每一列的数据再拼装结果。

**Comment by tianyong90** [comment]
👍  确实是个办法。目前设计的 picker 对于联动的场景支持确实不太友好了。每个列的值变化都会有 change 事件，而用户在 change 事件中修改列值又会再次产生 change 事件。这个也是下一版中主要要解决的问题。
