### ISSUE TITLE
Indicator组件  开启后瞬间关闭，关闭不了，可能是因为动画启动时间内触发不了关闭

### ISSUE THREAD

**Issue by kerwin-cn** [tianyong90/we-vue#9]
Indicator.open('Loading');
Indicator.close();

连续使用 可出现这个现象，关闭不了
可能一些需要等待时间短的地方使用会造成一直停留消除不了。

**Comment by tianyong90** [comment]
感谢反馈！ [v1.4.8](https://github.com/tianyong90/we-vue/releases/tag/v1.4.8) 中修正了这个问题。
:smile:
