### ISSUE TITLE
怎么样发布项目？npm run build?

### ISSUE THREAD

**Issue by sonygod** [tianyong90/we-vue#91]
怎么样发布项目？npm run build?

查看package.js 对应有几项

build:we-vue 提示错误？ 是不是全部要把build:XXXX 下面的全部运行一遍才出现dist目录？

发布出来后打开是404,编译过程提示 components 编译错误。

**Comment by tianyong90** [comment]
日常使用的话使用 npm/yarn 安装就可以了。主分支上现在是处于重构中的。

**Comment by sonygod** [comment]
现在只能部署在index 主页面下 /wwwroot 如果放到 /wwwroot/dist/这样就404,暂时先这样。

**Comment by sonygod** [comment]
另外：npm run build:demo 打包出来的4.XXX.js 大小超过2m,希望可以改进下
@tianyong90

**Comment by tianyong90** [comment]
感谢反馈。后面会优化下。

**Comment by sonygod** [comment]
这里记录下发布到二级目录方法，测试通过 假如是http://xxxx.com/dist/

1：全程不需要修改nginx

2: webpack.demo.conf.js 添加  `publicPath:'/dist/'`,

3: 修改路由 router/index.js

  ```
  path: '/dist' + `${nav.path}`,//15行

     path: '/dist/',//38行 
```

4：404暂时屏蔽没有测试
