### ISSUE TITLE
引用时报错

### ISSUE THREAD

**Issue by zhuxujin** [tianyong90/we-vue#97]
import WeVue from 'we-vue' 感觉这个没有引用对

**Comment by zhuxujin** [comment]
但是样式有的引用，有的引用不了

**Comment by tianyong90** [comment]
@zhuxujin 哪个版本？是如何引用的？贴下代码吧。

**Comment by zhuxujin** [comment]
import Vue from 'vue'
import WeVue from 'we-vue'
import Cookies from 'js-cookie'

import 'normalize.css/normalize.css' // A modern alternative to CSS resets

import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'

import '@/styles/index.scss' // global css

import 'we-vue/lib/style.css'

import App from './App'
import router from './router'
import store from './store'

import i18n from './lang' // Internationalization
import './icons' // icon
import './permission' // permission control

import * as filters from './filters' // global filters

import permission from '@/directive/permission/index.js' // 权限判断指令

Vue.use(WeVue)
Vue.use(Element, {
  size: Cookies.get('size') || 'medium', // set element-ui default size
  i18n: (key, value) => i18n.t(key, value)
})

Vue.directive('permission', permission)

// register global utility filters.
Object.keys(filters).forEach(key => {
  Vue.filter(key, filters[key])
})

Vue.config.productionTip = false

new Vue({
  el: '#app',
  router,
  store,
  i18n,
  render: h => h(App)
})

**Comment by zhuxujin** [comment]
是安装不成功的原因嘛（ps:是个小白，第一次使用）

**Comment by tianyong90** [comment]
> 但是样式有的引用，有的引用不了

@zhuxujin 用法是对的，这个具体什么情况？哪些引用不了？

**Comment by zhuxujin** [comment]
比如说我引用选择器示例
console报错：
vue.esm.js?efeb:628 [Vue warn]: Failed to resolve filter: pickerValueFilter

(found in <App> at src/App.vue)
vue.esm.js?efeb:628 [Vue warn]: Property or method "confirmPerson" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <App> at src/App.vue
       <Root>

**Comment by tianyong90** [comment]
这跟引用没关系。报错信息里解释的很清楚了，有个方法不存在。大概直接复制了在线示例的代码？实际使用时得按情况调整啊。

**Comment by zhuxujin** [comment]
明白了，以为复制过来的示例能直接使用呢，多谢
