### ISSUE TITLE
actionSheet中“取消”的回调函数缺失

### ISSUE THREAD

**Issue by debingfeng** [tianyong90/we-vue#98]
如何监听actionSheet的“取消"的操作。
![image](https://user-images.githubusercontent.com/9289886/53339072-374d1700-3940-11e9-892e-b5c09177b1cc.png)

**Comment by tianyong90** [comment]
刚发布的 v2.3 中，当点击 Cancel 项时会触发 cancel 事件，可以添加相应的处理函数，在其中处理“回调"。
